(function(){
	var u = undefined,
	e = function(d,m){
		var month = data[m - 1];
		if(month === u)
			return null;

		var day = month[d - 1];
		if(day === u)
			return null;

		var o = {
			name:day[0],
			label: day[1].length ? e.label[day[1]] : null
		};

		o.text = text.bind(null,o);
		return o;
	};

	e.text = function(d,m){
		return text( e(d,m) );
	};

	e.day = function(n){
		var d = new Date();
		if(n) d = new Date( d.getTime() + n*24*60*60*1000 );
		var m = d.getMonth()+1; d = d.getDate();
		return e(d,m);
	};

	e.label = {
		h:'Saint',
		f:'Sainte',
		m:'Saints'
	};

	var
	text = function(o){
		if(!o) return o; return o.label ? [ o.label, o.name ].join(' ') : o.name;
	},
	data = [
	[
		["Jour de l'An", ""],
		["Basile", "h"],
		["Geneviève", "f"],
		["Odilon", "h"],
		["Edouard", "h"],
		["Mélaine", "h"],
		["Raymond", "h"],
		["Lucien", "h"],
		["Alix", "f"],
		["Guillaume", "h"],
		["Pauline", "h"],
		["Tatiana", "f"],
		["Yvette", "f"],
		["Nina", "f"],
		["Rémi", "h"],
		["Marcel", "h"],
		["Roseline", "f"],
		["Prisca", "f"],
		["Marius", "h"],
		["Sébastien", "h"],
		["Agnès", "f"],
		["Vincent", "h"],
		["Barnard", "h"],
		["François de Sales", "h"],
		["Conversion de Paul", ""],
		["Paule", "f"],
		["Angèle", "f"],
		["Thomas d'Aquin", "h"],
		["Gildas", "h"],
		["Martine", "f"],
		["Marcelle", "f"]
	],[
		["Ella", "f"],
		["Fête de la Présention", ""],
		["Blaise", "h"],
		["Véronique", "f"],
		["Agathe", "f"],
		["Gaston", "h"],
		["Eugènie", "f"],
		["Jacqueline", "f"],
		["Apolline", "f"],
		["Arnaud", "h"],
		["Notre Dame de Lourdes", "f"],
		["Félix", "h"],
		["Béatrice", "f"],
		["Valentin", "h"],
		["Claude", "h"],
		["Julienne", "f"],
		["Alexis", "h"],
		["Bernadette", "f"],
		["Gabin", "h"],
		["Aimée", "f"],
		["Mercredi des Cendres", ""],
		["Isabelle", "f"],
		["Lazare", "h"],
		["Modeste", "f"],
		["Roméo", "h"],
		["Nestor", "h"],
		["Honorine", "f"],
		["Romain", "h"],
		["Auguste", "h"]
	],[
		["Aubin", "h"],
		["Charles le Bon", "h"],
		["Guénolé", "h"],
		["Casimir", "h"],
		["Olive", "h"],
		["Colette", "f"],
		["Félicité", "f"],
		["Jean de Dieu", "h"],
		["Françoise", "f"],
		["Vivien", "h"],
		["Rosine", "f"],
		["Justine", "f"],
		["Rodrigue", "h"],
		["Mathilde", "f"],
		["Louise", "f"],
		["Bénédicte", "f"],
		["Patrice", "h"],
		["Cyrille", "h"],
		["Joseph", "h"],
		["Herbert", "h"],
		["Clémence", "f"],
		["Léa", "f"],
		["Victorien", "h"],
		["Karine", "f"],
		["Anne", "f"],
		["Larissa", "f"],
		["Habib", "h"],
		["Gontran", "h"],
		["Gwladys", "f"],
		["Amédée", "h"],
		["Benjamin", "h"]
	],[
		["Hugues", "h"],
		["Sandrine", "f"],
		["Richard", "h"],
		["Isidore", "h"],
		["Irène", "f"],
		["Marcellin", "h"],
		["Jean-Baptiste de la Salle", "h"],
		["Julie", "f"],
		["Gautier", "h"],
		["Fulbert", "h"],
		["Stanislas", "h"],
		["Jules", "h"],
		["Ida", "f"],
		["Maxime", "h"],
		["Paterne", "h"],
		["Benoît-Joseph", "h"],
		["Anicet", "h"],
		["Parfait", "h"],
		["Emma", "f"],
		["Odette", "f"],
		["Anselme", "h"],
		["Alexandre", "h"],
		["Georges", "h"],
		["Fidèle", "h"],
		["Marc", "h"],
		["Alida", "f"],
		["Zita", "f"],
		["Valérie", "f"],
		["Catherine de Sienne", "f"],
		["Robert", "h"]
	],[
		["Fête du travail", ""],
		["Boris", "h"],
		["Philippe", "h"],
		["Sylvain", "h"],
		["Judith", "h"],
		["Prudence", "h"],
		["Gisèle", "f"],
		["Armistice de 1945", ""],
		["Pacôme", "h"],
		["Solange", "f"],
		["Estelle", "f"],
		["Achille", "h"],
		["Rolande", "f"],
		["Matthias", "h"],
		["Denise", "f"],
		["Honoré", "h"],
		["Pascal", "h"],
		["Eric", "h"],
		["Yves", "h"],
		["Bernardin", "h"],
		["Constantin", "h"],
		["Emile", "h"],
		["Didier", "h"],
		["Donatien", "h"],
		["Sophie", "f"],
		["Bérenger", "h"],
		["Augustin", "h"],
		["Germain", "h"],
		["Aymar", "h"],
		["Ferdinand", "h"],
		["Ferdinand", "h"]
	],[
		["Justin", "h"],
		["Blandine", "f"],
		["Kévin", "h"],
		["Clotilde", "f"],
		["Igor", "h"],
		["Norbert", "h"],
		["Gilbert", "h"],
		["Médard", "h"],
		["Diane", "f"],
		["Landry", "h"],
		["Barnabé", "h"],
		["Guy", "h"],
		["Antoine de Padoue", "h"],
		["Elisée", "f"],
		["Germaine", "f"],
		["Jean-François Régis", "h"],
		["Hervé", "h"],
		["Léonce", "h"],
		["Romuald", "h"],
		["Silvère", "h"],
		["Solstice d'été", ""],
		["Alban", "h"],
		["Audrey", "f"],
		["Jean-Baptiste", "h"],
		["Prosper", "h"],
		["Anthelme", "h"],
		["Fernand", "h"],
		["Irénée", "h"],
		["Pierre", "h"],
		["Martial", "h"]
	],[
		["Thierry", "h"],
		["Martinien", "h"],
		["Thomas", "h"],
		["Florent", "h"],
		["Antoine", "h"],
		["Mariette", "f"],
		["Raoul", "h"],
		["Thibault", "h"],
		["Amandine", "f"],
		["Ulrich", "h"],
		["Benoît", "h"],
		["Olivier", "h"],
		["Henri", "h"],
		["Fête Nationale", ""],
		["Donald", ""],
		["Fête de Notre Dame du Mont Carmel", ""],
		["Charlotte", "f"],
		["Frédéric", "h"],
		["Arsène", "h"],
		["Marina", "f"],
		["Victor", "h"],
		["Marie-Madeleine", "f"],
		["Brigitte", "f"],
		["Christine", "f"],
		["Jacques", "h"],
		["Anne", "f"],
		["Nathalie", "f"],
		["Samson", "h"],
		["Marthe", "f"],
		["Juliette", "f"],
		["Ignace de Loyola", "h"]
	],[
		["Alphonse", "h"],
		["Julien Eymard", "h"],
		["Lydie", "f"],
		["Jean-Marie Vianney", "h"],
		["Abel", "h"],
		["Fête de la Transfiguration", ""],
		["Gaétan", "h"],
		["Dominique", "h"],
		["Amour", "h"],
		["Laurent", "h"],
		["Claire", "f"],
		["Clarisse", "f"],
		["Hippolyte", "h"],
		["Evrard", "h"],
		["Fête de l'Assomption", ""],
		["Armel", "f"],
		["Hyacinthe", "h"],
		["Hélène", "f"],
		["Jean-Eudes", "h"],
		["Bernard", "h"],
		["Christophe", "h"],
		["Fabrice", "h"],
		["Rose de Lima", "f"],
		["Barthélémy", "h"],
		["Louis", "h"],
		["Natacha", "f"],
		["Monique", "f"],
		["Augustin", "h"],
		["Sabine", "f"],
		["Fiacre", "h"],
		["Aristide", "h"]
	],[
		["Gilles", "h"],
		["Ingrid", "f"],
		["Grégoire", "h"],
		["Rosalie", "f"],
		["Raïssa", "f"],
		["Bertrand", "h"],
		["Reine", "Sao,te"],
		["Fête de la Nativité", ""],
		["Alain", "h"],
		["Inès", "f"],
		["Adelphe", "h"],
		["Apollinaire", "h"],
		["Aimé", "h"],
		["Fête de la Croix Glorieuse", ""],
		["Roland", "h"],
		["Edith", "f"],
		["Renaud", "h"],
		["Nadège", "f"],
		["Emilie", "f"],
		["Davy", "h"],
		["Matthieu", "h"],
		["Maurice", "h"],
		["Equinoxe d'Automne", ""],
		["Thècle", "f"],
		["Hermann", "h"],
		["Côme", "h"],
		["Vincent de Paul", "h"],
		["Venceslas", "h"],
		["Michel", "h"],
		["Jérôme", "h"]
	],[
		["Thérèse de l'Enfant Jésus", "f"],
		["Léger", "h"],
		["Gérard", "h"],
		["François d'Assise", "h"],
		["Fleur", "f"],
		["Bruno", "h"],
		["Serge", "h"],
		["Pélagie", "f"],
		["Denis", "h"],
		["Ghislain", "h"],
		["Firmin", "h"],
		["Wilfried", "h"],
		["Géraud", "h"],
		["Juste", "h"],
		["Thérèse d'Avila", "h"],
		["Edwige", "f"],
		["Baudoin", "h"],
		["Luc", "h"],
		["René", "h"],
		["Adeline", "f"],
		["Céline", "f"],
		["Elodie", "f"],
		["Jean de Capistran", "h"],
		["Florentin", "h"],
		["Crépin", "h"],
		["Dimitri", "h"],
		["Emeline", "f"],
		["Jude", "h"],
		["Narcisse", "h"],
		["Bienvenue", "f"],
		["Quentin", "h"]
	],[
		["Toush", ""],
		["Fête des défunts", ""],
		["Hubert", "h"],
		["Charles", "h"],
		["Sylvie", "f"],
		["Bertille", "f"],
		["Carine", "f"],
		["Geoffroy", "h"],
		["Théodore", "h"],
		["Léon", "h"],
		["Armistice de 1918", ""],
		["Christian", "h"],
		["Brice", "h"],
		["Sidoine", "h"],
		["Albert", "h"],
		["Marguerite", "f"],
		["Elisabeth", "f"],
		["Aude", "f"],
		["Tanguy", "h"],
		["Edmond", "h"],
		["Présence de Marie", ""],
		["Cécile", "f"],
		["Clément", "h"],
		["Flora", "f"],
		["Catherine", "f"],
		["Delphine", "f"],
		["Sévrin", "h"],
		["Jacques de la Marche", "h"],
		["Saturnin", "h"],
		["André", "h"]
	],[
		["Florence", "f"],
		["Viviane", "f"],
		["François-Xavier", "h"],
		["Barbara", "f"],
		["Gérald", "h"],
		["Nicolas", "h"],
		["Ambroise", "f"],
		["Fête de l'Immaculée Conception", ""],
		["Pierre Fourier", "h"],
		["Romaric", "h"],
		["Daniel", "h"],
		["Jeanne-Françoise de Chantal", "f"],
		["Lucie", "f"],
		["Odile", "f"],
		["Ninon", "f"],
		["Alice", "f"],
		["Gaël", "h"],
		["Gatien", "h"],
		["Urbain", "h"],
		["Théophile", "h"],
		["Solstice d'Hiver", ""],
		["Françoise-Xavière", "f"],
		["Armand", "h"],
		["Adèle", "f"],
		["Noël", ""],
		["Etienne", "h"],
		["Jean", "h"],
		["Innocents", "m"],
		["David", "h"],
		["Roger", "h"],
		["Sylvestre", "h"]
	]];

	if(module) module.exports = e; else if(window) window.ephemeris = e;
})();
